platform :ios, '9.0'

target 'RnSqlite' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!


  node_modules_path = '../node_modules'

  pod 'Yoga', path: "#{node_modules_path}/react-native/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: "#{node_modules_path}/react-native"
  pod 'React-Core', path: "#{node_modules_path}/react-native/"
  pod 'React-CoreModules', path: "#{node_modules_path}/react-native/React/CoreModules"
  pod 'React-Core/DevSupport', path: "#{node_modules_path}/react-native/"
  pod 'React-RCTActionSheet', path: "#{node_modules_path}/react-native/Libraries/ActionSheetIOS"
  pod 'React-RCTAnimation', path: "#{node_modules_path}/react-native/Libraries/NativeAnimation"
  pod 'React-RCTBlob', path: "#{node_modules_path}/react-native/Libraries/Blob"
  pod 'React-RCTImage', path: "#{node_modules_path}/react-native/Libraries/Image"
  pod 'React-RCTLinking', path: "#{node_modules_path}/react-native/Libraries/LinkingIOS"
  pod 'React-RCTNetwork', path: "#{node_modules_path}/react-native/Libraries/Network"
  pod 'React-RCTSettings', path: "#{node_modules_path}/react-native/Libraries/Settings"
  pod 'React-RCTText', path: "#{node_modules_path}/react-native/Libraries/Text"
  pod 'React-RCTVibration', path: "#{node_modules_path}/react-native/Libraries/Vibration"
  pod 'React-Core/RCTWebSocket', path: "#{node_modules_path}/react-native/"

  pod 'React-cxxreact', path: "#{node_modules_path}/react-native/ReactCommon/cxxreact"
  pod 'React-jsi', path: "#{node_modules_path}/react-native/ReactCommon/jsi"
  pod 'React-jsiexecutor', path: "#{node_modules_path}/react-native/ReactCommon/jsiexecutor"
  pod 'React-jsinspector', path: "#{node_modules_path}/react-native/ReactCommon/jsinspector"
  pod 'ReactCommon/callinvoker', path: "#{node_modules_path}/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', path: "#{node_modules_path}/react-native/ReactCommon"

  pod 'RCTRequired', path: "#{node_modules_path}/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', path: "#{node_modules_path}/react-native/Libraries/TypeSafety"
  pod 'FBLazyVector', path: "#{node_modules_path}/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', path: "#{node_modules_path}/react-native/Libraries/FBReactNativeSpec"
  pod 'Folly', podspec: "#{node_modules_path}/react-native/third-party-podspecs/Folly.podspec"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5'
    end
  end
end
